---

name: "✨ 기능 추가 요청 (Feature Request)"
about: 새로운 기능 구현 또는 개선 작업을 위한 이슈를 생성합니다.
title: "타입: 기능 개요"
labels: ["feature"]
assignees: []

body:

- type: textarea
  id: summary
  attributes:
  label: "📝 개요 (Summary)"
  description: 구현할 기능에 대한 간단하고 명확한 설명을 작성해주세요.
  placeholder: 예) 와인 상세 페이지에서 즐겨찾기 버튼 기능을 구현합니다.
  validations:
  required: true

- type: textarea
  id: details
  attributes:
  label: "🔍 세부 설명 (Details)"
  description: 이 기능이 필요한 이유, 구현 시 고려할 사항 등을 상세히 설명해주세요.
  placeholder: | - 사용자에게 즐겨찾기 기능을 제공해 선호 와인을 저장할 수 있게 함 - 버튼 클릭 시 API 호출 → UI 반영까지 포함
  validations:
  required: false

- type: checkboxes
  id: scope
  attributes:
  label: "📦 작업 범위 (Scope)"
  description: 어떤 범위의 작업이 포함되는지 선택하거나 추가로 작성해주세요.
  options: - label: UI 컴포넌트 생성 또는 수정 - label: 상태 관리(Store) 연동 - label: API 연동 / 비즈니스 로직 작성 - label: 입력값 검증 / 에러 처리 - label: 반응형 및 접근성 고려 - label: 테스트 코드 작성

- type: textarea
  id: acceptance-criteria
  attributes:
  label: "✅ 완료 기준 (Acceptance Criteria)"
  description: 이 기능이 완료되었는지 판단할 수 있는 명확한 기준을 작성해주세요.
  placeholder: | - 즐겨찾기 버튼 클릭 시 API 요청이 발생한다. - 요청 성공 시 버튼 상태가 변경된다. - 요청 실패 시 사용자에게 알림이 표시된다.
  validations:
  required: true

- type: textarea
  id: dependencies
  attributes:
  label: "🔗 관련 작업 (Dependencies)"
  description: 이 작업과 관련되거나 선행되어야 할 작업이 있다면 링크 또는 번호로 연결해주세요.
  placeholder: 예) 관련 이슈: #42, 관련 PR: #101
  validations:
  required: false

- type: textarea
  id: notes
  attributes:
  label: "💬 추가 참고 사항 (Notes)"
  description: 리뷰어나 팀원에게 전달하고 싶은 추가 사항이 있다면 작성해주세요.
  placeholder: 예) 이슈를 분리할지 고민 중입니다. 피드백 부탁드립니다.
  validations:
  required: false
